import pygame
from pygame.math import *
from pathlib import Path

SCREEN = None
SCREENRECT = None
CURRSCREEN = None

WINDOWWIDTH, WINDOWHEIGHT = 3840, 2160

CELLSIZE = 20
CELLGAP = 0.99
CELLOFFSETT = Vector2(0,0)

HANDLER = None

CELLALIVECOLOR = [255,255,255]
CELLDEADCOLOR = [0,0,0]
CELLUNTOUCHCOLOR = [200,60,60]
BACKGROUNDCOLOR = [50,0,0]
TEXTCOLOR = [255,255,255]
INPUTUICOLOR = [30,30,30,255]
SELECTEDUICOLOR = [10,10,10,255]

ARROWCURSOR = pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_ARROW)
IBEAMCURSOR = pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_IBEAM)
HANDCURSOR  = pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_HAND)

CURRENTDIR = Path(__file__).parent

ATTRIBUTESSAVEPATH   = CURRENTDIR / 'Data/AttributePresets.json'
LOADDATASAVEPATH     = CURRENTDIR / 'Data/ColorData.json'
COLORPRESETSSAVEPATH = CURRENTDIR / 'Data/ColorPresets.json'