import pygame
from pygame.math import *

SCREEN = None
SCREENRECT = None
CURRSCREEN = None

WINDOWWIDTH, WINDOWHEIGHT = 3840, 2160
# WINDOWWIDTH, WINDOWHEIGHT = 640, 480

CELLSIZE = 20
CELLGAP = 0.99
CELLOFFSETT = Vector2(0,0)

HANDLER = None

CELLALIVECOLOR = (255,255,255)
CELLDEADCOLOR = (0,0,0)
CELLUNTOUCHCOLOR = (200,60,60)
BACKGROUNDCOLOR = (50,0,0)

SELECTEDUICOLOR = (10,10,10,255)

ARROWCURSOR = pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_ARROW)
IBEAMCURSOR = pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_IBEAM)
HANDCURSOR  = pygame.cursors.Cursor(pygame.SYSTEM_CURSOR_HAND)

SETTINGSSAVEPATH = 'Python_Game_Files/Data/SavedAttributes.json'